### ISSUE TITLE
Acknowledgement of commands

### ISSUE THREAD

**Issue by dmcomm** [mechawrench/wificom-webapp#5]
It would be good if the WiFiCom acknowledged commands and the website status messages could say something different depending on whether this happened or not. As a first step, the webapp could add a unique ID to commands? Then at some point wificom-lib can respond? Then after that the webapp could be updated to do something with the response?

**Comment by mechawrench** [comment]
Implemented on QA, will go live with the next release of wificom-lib

**Comment by dmcomm** [comment]
Thinking about the delay, I reckon the app would feel more responsive if it put some text immediately saying it's attempting to do whatever, then updates that text to the result when available.

**Comment by mechawrench** [comment]
Great idea, I'll look into a spinner and some text describing what's
happening

On November 12, 2022, GitHub ***@***.***> wrote:
> Thinking about the delay, I reckon the app would feel more responsive
> if it put some text immediately saying it's attempting to do whatever,
> then updates that text to the result when available.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/mechawrench/wificom-webapp/issues/5#issuecomment-
1312614486>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AB2IL3YQKK74QP6SBNM7C4TWIBB5RANCNFSM6AAAAAARWVLBJQ>.
You are receiving this because you commented.Message ID:
***@***.***>

**Comment by dmcomm** [comment]
See #10
